source 'https://rubygems.org'

gem 'activesupport'
gem 'capybara', '2.13.0'
gem 'cucumber', '2.3.0'
gem 'psych'
gem 'rest-client'
gem 'rspec', '~> 3.5'
gem 'selenium-webdriver', '2.53.4'
gem 'chromedriver-helper', '~> 1.0'

